NXT_APP_ID: 'mOc4pNPDBkG9RCP-2qxA5QcqI-OChIkQa4D6Gp-CWks'
NXT_APP_SECRET: '-jWS400VmL-D_0yq-brwsqpQ_pdEGfz7bwXn8V650MY'
NXT_APP_URL: 'https://fashionxt-crm-test.herokuapp.com/'
  #NXT_APP_ID: 'vvxyQoNnhTlO93B8AmwxrreJ2E6zqsSIm12gDv5pEf4'
  #NXT_APP_SECRET: '0kM9AafsZThnknThlJFBoQoX1Ha88j8UOGWq61woxVg'
  #NXT_APP_URL: 'http://127.0.0.1:3000/'
