# Development examples, for production set environment variables on the server
# E.g. if using Heroku, set the variables using: heroku config:set NXT_APP_ID="<uid>"
# NXT_APP_ID: 'vvxyQoNnhTlO93B8AmwxrreJ2E6zqsSIm12gDv5pEf4'
# NXT_APP_SECRET: '0kM9AafsZThnknThlJFBoQoX1Ha88j8UOGWq61woxVg'
# NXT_APP_URL: 'http://127.0.0.1:3000/' # The OAuth Provider URL, not the client app URL
